title: Binita Shrestha # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Learner 
  <br><br>
  I have a Master’s degree in Water Resources Engineering and currently enrolled as a CS grad student. I started my career as an H&H Engineer in 2021. I have 4 years of experience with several phases of FEMA Risk Mapping: Base Level Engineering (BLE 2D HEC-RAS modeling), Discovery (Technical report, Community Outreach, Documentation), Hydrologic analysis (RRE flow calculation), Hydraulic analysis (1D HEC-RAS riverine modeling, floodway study), and QA QC. I am also experienced in Mississippi Department of Environmental Quality (MDEQ) dam inundation modeling (combined 1D-2D RAS models), identification of areas of mitigation interest (AOMI, FEMA non-reg products), and Natural Resources Conservation Services (NRCS) watershed assessment project (hydrologic modeling in HSPF: BASIN45).  
  <br><br>
  <a href="https://www.linkedin.com/in/binita-shrestha/">View My LinkedIn Profile</a> 
  <br><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

